name: Test
on: [ push, pull_request ]

jobs:
  deploy:
    if: startsWith(github.repository, 'MelanX')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.0
        with:
          node-version: "17"

      - name: Install dependencies
        run: npm i

      - name: Test
        run: npm run test
