name: Test
on: [ push, pull_request ]

jobs:
  deploy:
    if: startsWith(github.repository, 'MelanX')
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.0

      - name: npm/yarn/pnpm install
        uses: Jaid/action-npm-install@v1.2.4

      - name: Test
        run: npm run test
